// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0qq5hN6hqw0SsQvczWg2hbm5vAufjvXs',
    appId: '1:693384841272:ios:90e470901be80cd777becd',
    messagingSenderId: '693384841272',
    projectId: 'driving-school-6e78e',
    storageBucket: 'driving-school-6e78e.appspot.com',
    iosBundleId: 'com.example.newProjectDriving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0qq5hN6hqw0SsQvczWg2hbm5vAufjvXs',
    appId: '1:693384841272:ios:90e470901be80cd777becd',
    messagingSenderId: '693384841272',
    projectId: 'driving-school-6e78e',
    storageBucket: 'driving-school-6e78e.appspot.com',
    iosBundleId: 'com.example.newProjectDriving',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxcSjfdNFCPuMc_oYbZJNwRe9snW5FnRA',
    appId: '1:693384841272:web:119aea8e1d7008c877becd',
    messagingSenderId: '693384841272',
    projectId: 'driving-school-6e78e',
    authDomain: 'driving-school-6e78e.firebaseapp.com',
    storageBucket: 'driving-school-6e78e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHah0nNCIBpQSbtBN-6LR13h58dHJVu58',
    appId: '1:693384841272:android:a525c41697fd7a8277becd',
    messagingSenderId: '693384841272',
    projectId: 'driving-school-6e78e',
    storageBucket: 'driving-school-6e78e.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxcSjfdNFCPuMc_oYbZJNwRe9snW5FnRA',
    appId: '1:693384841272:web:2429292bfcbcec7077becd',
    messagingSenderId: '693384841272',
    projectId: 'driving-school-6e78e',
    authDomain: 'driving-school-6e78e.firebaseapp.com',
    storageBucket: 'driving-school-6e78e.appspot.com',
  );

}